apiVersion: apps/v1
kind: Deployment
metadata:
  name: waf-backend
  labels:
    app: waf-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waf-backend
  template:
    metadata:
      labels:
        app: waf-backend
    spec:
      serviceAccountName: waf-backend-sa
      containers:
      - name: waf-backend
        image: waf-backend:v3.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: GIN_MODE
          value: "release"
        - name: PORT
          value: "8080"
        - name: CORS_ORIGIN
          value: "*"
        - name: LOG_LEVEL
          value: "info"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: waf-secrets
              key: jwt-secret
              optional: true
        - name: INGRESS_URL
          value: "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local"  # Ingress Service
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: waf-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: waf-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URL
          value: "http://localhost:80/auth/callback"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi