apiVersion: v1
kind: Service
metadata:
  name: waf-frontend-service
  labels:
    app: waf-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: waf-frontend