# WAF System Environment Configuration
# Central configuration for all URLs and endpoints

environments:
  local:
    frontend_url: "http://localhost:3000"
    backend_url: "http://localhost:3000/api"
    websocket_url: "ws://localhost:3000/api/v1/ws"
    target_url: "http://localhost:3000"  # For security tests
    oauth_redirect: "http://localhost:3000/auth/callback"
    
  docker:
    frontend_url: "http://localhost"
    backend_url: "http://localhost/api"
    websocket_url: "ws://localhost/api/v1/ws"
    target_url: "http://localhost"
    oauth_redirect: "http://localhost/auth/callback"

# Current active environment
current_environment: "local"